#!/bin/bash 
#
# Copyright (C) 2014, Coder of Salvation / Leon van Kammen 
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# this will hold specific curl options (when webpipes need authorisation)
declare -A CURL_OPTIONS
declare -A WEBPIPES 
TMPFILE="/tmp/.$(whoami).webpipe"

webpipe::set(){
  case "$1" in
    curloptions) CURL_OPTIONS["$2"]="$3"      ;;
    webpipe)    cmd="$(basename $2)"; WEBPIPES["$cmd"]="$2"; alias $cmd="webpipe::get $cmd";;
  esac
}

webpipe::get_domain(){
  domain="${1/http:/}"; domain="${domain/https:/}"; domain="${domain/\/\//}"; domain="${domain//\/*/}"; 
  printf "$domain"
}

webpipe::get(){
  url="${WEBPIPES[$1]}";
  domain="$(webpipe::get_domain "$url")"
  declare -A CURL_OPTIONS # bash bug? we need to do this again
  curloptions="${CURL_OPTIONS["$domain"]}"
  [[ "${#url}" == 0   ]] && return 1;
  [[ "$2" == "--help" ]] && method="-X OPTIONS" || method="-X POST"
  [[ ! -n $OUTPUT     ]] && type="text/plain" || type="$OUTPUT"
  [[ -t 0 ]] && POST="" || POST="-d "$(cat -)""
  curl -L -s ${method} ${curloptions} ${POST} -H "Content-Type: $type" "$url"
  return $?
}

webpipe::index(){
  domain="$(webpipe::get_domain "$1")"
  declare -A CURL_OPTIONS # bash bug? we need to do this again
  curloptions="${CURL_OPTIONS["$domain"]}"
  pipes="$(curl -L -s ${curloptions} "$1")"; (( $? > 0 )) && { echo "could not fetch $url"; return 1; }
  if [[ "$pipes" =~ "<" ]] || [[ "$pipes" =~ "{" ]]; then echo "$pipes"; return 1; fi 
  echo "$pipes" > $TMPFILE
  while read url; do 
    echo "webpipe> adding $url"
    webpipe::set webpipe "$url"
  done < $TMPFILE
}

